### ISSUE TITLE
Place Characterization - Aggregation

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/GEEST#113]

**Comment by mvmaltitz** [comment]
I am getting the following output which is incorrect and makes the output smaller that it should be:


![Image](https://github.com/user-attachments/assets/5db41d82-16ae-4fe7-865f-886d48a982f2)

The inputs are:


![Image](https://github.com/user-attachments/assets/7c31086c-9b92-486f-b69b-e477f947cb8b)



![Image](https://github.com/user-attachments/assets/50e6698c-956e-4b9c-ab05-bcc9237ae191)

**Comment by dimasciput** [comment]
Found the issue is due to the difference in metadata for each raster layer.

Proposed workaround : loop through all the layers and find the largest transform : 

```
def find_largest_transform(raster_files):
    transforms = []
    for raster_file in raster_files:
        with rasterio.open(raster_file) as src:
            transforms.append(src.transform)

    largest_transform = max(transforms, key=lambda t: abs(t.a * t.e - t.b * t.d))

    return largest_transform
```

```
largest_transform = find_largest_transform(rasLayers)
meta1.update(transform=largest_transform)
```

**Comment by ClaraIV** [comment]
Please ensure the testing is performed using every possible combination of data inputs for each factor (eg. For Safety: use all options, iteratively). Thanks! 
@osundwajeff @mvmaltitz @dragosgontariu

**Comment by mvmaltitz** [comment]
Input layers:


![Image](https://github.com/user-attachments/assets/daf19f6f-e497-4660-af6c-c880ffd4f03a)




![Image](https://github.com/user-attachments/assets/4f6bce4d-a4fb-409b-8193-ea0af83c4243)



![Image](https://github.com/user-attachments/assets/042b66e9-6304-4822-ab0b-8380d869c340)



![Image](https://github.com/user-attachments/assets/874d2706-b8cf-483c-b28d-e91c72ccdb37)



![Image](https://github.com/user-attachments/assets/c54e71cc-16ff-478c-9b4d-995e37f8be2c)



![Image](https://github.com/user-attachments/assets/f0dbbd2b-3667-471b-93b6-5118e50a1722)



![Image](https://github.com/user-attachments/assets/9fffe336-15eb-450f-be68-ff4aa8505f7b)




![Image](https://github.com/user-attachments/assets/1dfa74bd-eff8-4438-b203-88b885ed4d44)

Results:


![Image](https://github.com/user-attachments/assets/e3d073a6-71f6-419b-b80f-c2c67284cea2)

@dragosgontariu

**Comment by mvmaltitz** [comment]
@javaftw @osundwajeff 

I get the following error message and no place score error. 


![Image](https://github.com/user-attachments/assets/1288ef67-d87d-4449-b1c8-d50ed825c8ca)

**Comment by mvmaltitz** [comment]
@timlinux 

Using self and manually generated other Factors that failed during process via Plugin, the Place score aggregation also experiencing an error with trigger Python error below

```
2024-09-12T23:18:14     WARNING    Traceback (most recent call last):
              File "C:\Users/benny/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gender_indicator_tool\gender_indicator_tool.py", line 6320, in place_characterization_aggregation
              (np.where(WLK_ras != -9999, WLK_ras, 0) * WLK_weight / 100) +
             ValueError: operands could not be broadcast together with shapes (10756,4352) (10756,4364) 
```

![Screenshot 2024-09-12 232044](https://github.com/user-attachments/assets/8cb08d68-72cf-458a-8da4-8ecb14d27999)

And Python warning below

```
2024-09-12T23:18:14     WARNING    warning:C:\Users/benny/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gender_indicator_tool\gender_indicator_tool.py:6320: RuntimeWarning: overflow encountered in multiply
              (np.where(WLK_ras != -9999, WLK_ras, 0) * WLK_weight / 100) +
             
             traceback: File "C:\Users/benny/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gender_indicator_tool\gender_indicator_tool.py", line 6320, in place_characterization_aggregation
              (np.where(WLK_ras != -9999, WLK_ras, 0) * WLK_weight / 100) +
```
