### ISSUE TITLE
Factor: Workplace Discrimination

### ISSUE THREAD

**Issue by timlinux** [kartoza/GEEST#36]
![image](https://github.com/kartoza/GEEST/assets/178003/5f034358-1373-4057-92c7-07e719b60022)

Check and ensure that we have unit tests, implementation and verified results for this indicator

**Comment by dragosgontariu** [comment]
error encountered:

Could not create layer D:/Munca/WB/Geest/St_Lucia/Testing/07082024/temp/countryBuff.shp: Creation of layer failed (OGR error: Failed to create file D:/Munca/WB/Geest/St_Lucia/Testing/07082024/temp\countryBuff.shp: No such file or directory)

@osundwajeff @mvmaltitz @javaftw

**Comment by mvmaltitz** [comment]
Input:


![Image](https://github.com/user-attachments/assets/552b46cb-53ef-4cf0-9455-3b7dae1272ad)



Result:


![Image](https://github.com/user-attachments/assets/79339c13-897c-46d4-9a31-d70f131ca639)

@dragosgontariu

**Comment by mvmaltitz** [comment]
### Contextual

Each Factors in Contextual Dimension completed. 

![Screenshot 2024-09-12 190112](https://github.com/user-attachments/assets/9520b8b0-1679-49bf-a5cc-0d1ce345d3ee)

Contextual_score also succeed with some Python error. Although the Contextual_score.tif exist but the value is incorrect, then it means the script failed to generate the correct value and save as a file.

```
2024-09-12T19:06:09     WARNING    Traceback (most recent call last):
              File "C:\Users/benny/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gender_indicator_tool\gender_indicator_tool.py", line 6009, in contextual_aggregation
              with rasterio.open(aggregation, "w", **meta1) as dst:
              File "C:\Users\benny\AppData\Roaming\Python\Python39\site-packages\rasterio\env.py", line 451, in wrapper
              return f(*args, **kwds)
              File "C:\Users\benny\AppData\Roaming\Python\Python39\site-packages\rasterio\__init__.py", line 341, in open
              dataset = writer(
              File "rasterio\\_io.pyx", line 1464, in rasterio._io.DatasetWriterBase.__init__
              File "rasterio\\_io.pyx", line 330, in rasterio._io._delete_dataset_if_exists
              File "rasterio\\_err.pyx", line 195, in rasterio._err.exc_wrap_int
             rasterio._err.CPLE_AppDefinedError: Deleting Contextual_score.tif failed: Permission denied
```
