### ISSUE TITLE
Factor: Active Transport- Subfactor: Location of street crossings

### ISSUE THREAD

**Issue by amyburness** [kartoza/GEEST#42]
````
[out:xml] [timeout:25];
 {{geocodeArea:Saint Lucia}} -> .area_0;
(
    node["highway"="crossing"](area.area_0);
    node["railway"="crossing"](area.area_0);
    way["highway"="crossing"](area.area_0);
    way["railway"="crossing"](area.area_0);
    relation["highway"="crossing"](area.area_0);
    relation["railway"="crossing"](area.area_0);
);
(._;>;);
out body;
````

This factor is assessed through network analyses to calculate catchment areas using Open Route Service. After each analysis, the territory is divided into 100m x 100m rasters, and the factor score is calculated as the average score within each raster. The scoring for each type of facility is categorized by distance as follows:

0 to 400 meters: 5
401 to 800 meters: 4
801 to 1200 meters: 3
1201 to 1500 meters: 2
1501 to 2000 meters: 1
Over 2000 meters: 0

**Comment by amyburness** [comment]
Use QuickOSM plugin in QGIS

**Comment by carolinamayh** [comment]
Similar to Women's Travel Patterns, Active Transport is assessed by evaluating several subfactors, including the location of street crossings. The final score for Active Transport should be the average of the subfactor scores per raster. The tool's interface should not include separate tabs for each subfactor. Please note that the methodology and name for this specific factor, Active Transport, were incorrect in the first version of the GEEST. @osundwajeff

**Comment by dragosgontariu** [comment]
1. the thresholds should be treated like for the rest of the sub factors:

Street Crossings (indicates safety and accessibility; measured by availability/presence per raster cell)
•	0: No crossings
•	3: 1 crossing 
•	5: 2 or more crossings

2.  error encountered:

2024-08-07T12:09:25     INFO    GDAL command:
2024-08-07T12:09:25     INFO    gdal_rasterize -l INPUT -a reclass_val -ts 263.0 487.0 -ot Float32 -of GTiff C:/Users/Dragos/AppData/Local/Temp/processing_YZEcFO/525bd6a5d11442ae80a180dadb0f12dc/INPUT.gpkg AT__cycle_paths_lines.tif
2024-08-07T12:09:25     INFO    GDAL command output:
2024-08-07T12:09:25     CRITICAL    Process returned error code 1
2024-08-07T12:09:25     INFO    Results: {'OUTPUT': 'AT__cycle_paths_lines.tif'}
2024-08-07T12:09:27     INFO    Results: {'OUTPUT': 'output_8bb027b8_0234_40ad_bb3d_b0f9e7a42ded'}
2024-08-07T12:09:27     CRITICAL    ERROR 1: Failed to find field reclass_val on layer INPUT, skipping.
2024-08-07T12:20:28     INFO    Results: {'OUTPUT': 'output_ebde8f65_68ff_4f9f_8427_1f44491e0767'}
2024-08-07T12:20:32     INFO    Results: {'OUTPUT': 'D:/Munca/WB/Geest/St_Lucia/Testing/07082024//temp/grid.shp'}
2024-08-07T12:20:33     INFO    ogr2ogr D:/Munca/WB/Geest/St_Lucia/Testing/07082024//temp/roadBuf.shp D:/Munca/WB/Geest/St_Lucia/Testing/07082024//temp/Scored_roads_cycle_paths_lines.shp -dialect sqlite -sql "SELECT ST_Buffer(geometry, 50.0) AS geometry,* FROM """Scored_roads_cycle_paths_lines"""" -f "ESRI Shapefile"
2024-08-07T12:20:33     INFO    GDAL command:
2024-08-07T12:20:33     INFO    ogr2ogr D:/Munca/WB/Geest/St_Lucia/Testing/07082024//temp/roadBuf.shp D:/Munca/WB/Geest/St_Lucia/Testing/07082024//temp/Scored_roads_cycle_paths_lines.shp -dialect sqlite -sql "SELECT ST_Buffer(geometry, 50.0) AS geometry,* FROM """Scored_roads_cycle_paths_lines"""" -f "ESRI Shapefile"
2024-08-07T12:20:33     INFO    GDAL command output:
2024-08-07T12:20:33     INFO    Process completed successfully
2024-08-07T12:20:33     INFO    Results: {'OUTPUT': 'D:/Munca/WB/Geest/St_Lucia/Testing/07082024//temp/roadBuf.shp'}
2024-08-07T12:20:37     INFO    Taking destination CRS EPSG:32620 from layer
2024-08-07T12:20:37     INFO    Setting output type to MultiPolygon
2024-08-07T12:20:37     INFO    Packaging layer 1/1: grid
2024-08-07T12:20:38     INFO    Results: {'OUTPUT': 'output_fcc3cfd1_35e4_46f9_bf10_d891b88ebdf2'}
2024-08-07T12:20:48     INFO    gdal_rasterize -l INPUT -a reclass_val -ts 263.0 487.0 -ot Float32 -of GTiff C:/Users/Dragos/AppData/Local/Temp/processing_YZEcFO/7c2d727edfaa47899b137421033e3897/INPUT.gpkg AT__cycle_paths_lines.tif
2024-08-07T12:20:48     INFO    GDAL command:
2024-08-07T12:20:48     INFO    gdal_rasterize -l INPUT -a reclass_val -ts 263.0 487.0 -ot Float32 -of GTiff C:/Users/Dragos/AppData/Local/Temp/processing_YZEcFO/7c2d727edfaa47899b137421033e3897/INPUT.gpkg AT__cycle_paths_lines.tif
2024-08-07T12:20:48     INFO    GDAL command output:
2024-08-07T12:20:49     CRITICAL    Process returned error code 1
2024-08-07T12:20:49     INFO    Results: {'OUTPUT': 'AT__cycle_paths_lines.tif'}
2024-08-07T12:20:51     INFO    Results: {'OUTPUT': 'output_058ee321_32d7_4d2f_9c4d_90fe9eee2d7f'}
2024-08-07T12:20:51     CRITICAL    ERROR 1: Failed to find field reclass_val on layer INPUT, skipping.

Traceback (most recent call last):
              File "C:\Users/Dragos/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gender_indicator_tool\gender_indicator_tool.py", line 2430, in walkability
              grid_result = processing.run('native:creategrid', grid_params)
              File "C:\PROGRA~1/QGIS 3.32.0/apps/qgis/./python/plugins\processing\tools\general.py", line 106, in run
              return Processing.runAlgorithm(algOrName, parameters, onFinish, feedback, context)
              File "C:\PROGRA~1/QGIS 3.32.0/apps/qgis/./python/plugins\processing\core\Processing.py", line 176, in runAlgorithm
              ret, results = execute(alg, parameters, context, feedback, catch_exceptions=False)
              File "C:\PROGRA~1/QGIS 3.32.0/apps/qgis/./python/plugins\processing\gui\AlgorithmExecutor.py", line 70, in execute
              results, ok = alg.run(parameters, context, feedback, {}, False)
             _core.QgsProcessingException: Could not create layer D:/Munca/WB/Geest/St_Lucia/Testing/07082024//temp/grid.shp: Creation of data source failed (OGR error: D:/Munca/WB/Geest/St_Lucia/Testing/07082024//temp/grid.shp is not a directory.)

@osundwajeff @mvmaltitz

**Comment by mvmaltitz** [comment]
Result:


![Image](https://github.com/user-attachments/assets/489b8b56-75b7-42fa-ad59-128dda12fba9)



![Image](https://github.com/user-attachments/assets/e4062024-383e-451c-9c1f-48119f18c1f7)

@dragosgontariu

**Comment by mvmaltitz** [comment]
@dragosgontariu 

The pixels are now representative of the point above them

![Image](https://github.com/user-attachments/assets/f77e21c0-e5d6-4289-bfe4-f566a585ec6e)

**Comment by dragosgontariu** [comment]
Hi @osundwajeff @mvmaltitz @javaftw @bennyistanto @carolinamayh @ClaraIV

As previously discussed, we are currently running tests in two other countries (Fiji and Tunisia). However, we encountered issues with the Active Transport tab. In my case, the tool crashed entirely. In Benny's case, the "processing" message remains indefinitely, without generating any outputs.

We will provide you with the input data shortly so that you can replicate the tests on your end.

**Comment by dragosgontariu** [comment]
data for FIJI: https://we.tl/t-0VJLM0KuQj

**Comment by mvmaltitz** [comment]
@dragosgontariu please could you provide us with additional data. 
Could you include a screenshot of the setup as well as any error messages that may have occurred.

**Comment by bennyistanto** [comment]
I managed to to test using Tunisia data, unfortunately the active transport failed without any error information, it just Not Responding (see attached picture below) after I clicked the Execute button on Step 1 and the label "Processing..." appear. I have tried it on two machines with the same result.

![Screenshot 2024-09-06 090753](https://github.com/user-attachments/assets/14e76bb7-cdca-4bcd-a912-58ea2225b8df)

Data for testing:
[active_transport.zip](https://github.com/user-attachments/files/16909571/active_transport.zip)

I am using the latest plugin sent by Michelle today, and QGIS LTR 3.34.4
