### ISSUE TITLE
Factor: Active Transport- Subfactor: Location of cycle paths (OSM)

### ISSUE THREAD

**Issue by amyburness** [kartoza/GEEST#45]
````
[out:xml] [timeout:25];
 {{geocodeArea:Saint Lucia}} -> .area_0;
(
    node["highway"="cycleway"](area.area_0);
    node["highway"="track"](area.area_0);
    node["cycleway"="track"](area.area_0);
    node["cycleway"="lane"](area.area_0);
    node["cycleway"="share_busway"](area.area_0);
    node["cycleway"="shared_lane"](area.area_0);
    way["highway"="cycleway"](area.area_0);
    way["highway"="track"](area.area_0);
    way["cycleway"="track"](area.area_0);
    way["cycleway"="lane"](area.area_0);
    way["cycleway"="share_busway"](area.area_0);
    way["cycleway"="shared_lane"](area.area_0);
    relation["highway"="cycleway"](area.area_0);
    relation["highway"="track"](area.area_0);
    relation["cycleway"="track"](area.area_0);
    relation["cycleway"="lane"](area.area_0);
    relation["cycleway"="share_busway"](area.area_0);
    relation["cycleway"="shared_lane"](area.area_0);
);
(._;>;);
out body;
````

This indicator is composed by calculating the average of these four factors. First, the territory needs to be divided into 100m x 100m rasters.

2. Cycle Paths (measured by availability/presence per raster)
•	0: No cycle paths
•	3: 1 cycle path 
•	5: 2 or more cycle paths

**Comment by carolinamayh** [comment]
Similar to Women's Travel Patterns, Active Transport is assessed by evaluating several subfactors, including the location of cycle paths. The final score for Active Transport should be the average of the subfactor scores per raster. The tool's interface should not include separate tabs for each subfactor. Please note that the methodology and name for this specific factor, Active Transport, were incorrect in the first version of the GEEST. @osundwajeff

**Comment by dragosgontariu** [comment]
error encountered:

2024-08-07T12:09:25     INFO    GDAL command:
2024-08-07T12:09:25     INFO    gdal_rasterize -l INPUT -a reclass_val -ts 263.0 487.0 -ot Float32 -of GTiff C:/Users/Dragos/AppData/Local/Temp/processing_YZEcFO/525bd6a5d11442ae80a180dadb0f12dc/INPUT.gpkg AT__cycle_paths_lines.tif
2024-08-07T12:09:25     INFO    GDAL command output:
2024-08-07T12:09:25     CRITICAL    Process returned error code 1
2024-08-07T12:09:25     INFO    Results: {'OUTPUT': 'AT__cycle_paths_lines.tif'}
2024-08-07T12:09:27     INFO    Results: {'OUTPUT': 'output_8bb027b8_0234_40ad_bb3d_b0f9e7a42ded'}
2024-08-07T12:09:27     CRITICAL    ERROR 1: Failed to find field reclass_val on layer INPUT, skipping.
2024-08-07T12:20:28     INFO    Results: {'OUTPUT': 'output_ebde8f65_68ff_4f9f_8427_1f44491e0767'}
2024-08-07T12:20:32     INFO    Results: {'OUTPUT': 'D:/Munca/WB/Geest/St_Lucia/Testing/07082024//temp/grid.shp'}
2024-08-07T12:20:33     INFO    ogr2ogr D:/Munca/WB/Geest/St_Lucia/Testing/07082024//temp/roadBuf.shp D:/Munca/WB/Geest/St_Lucia/Testing/07082024//temp/Scored_roads_cycle_paths_lines.shp -dialect sqlite -sql "SELECT ST_Buffer(geometry, 50.0) AS geometry,* FROM """Scored_roads_cycle_paths_lines"""" -f "ESRI Shapefile"
2024-08-07T12:20:33     INFO    GDAL command:
2024-08-07T12:20:33     INFO    ogr2ogr D:/Munca/WB/Geest/St_Lucia/Testing/07082024//temp/roadBuf.shp D:/Munca/WB/Geest/St_Lucia/Testing/07082024//temp/Scored_roads_cycle_paths_lines.shp -dialect sqlite -sql "SELECT ST_Buffer(geometry, 50.0) AS geometry,* FROM """Scored_roads_cycle_paths_lines"""" -f "ESRI Shapefile"
2024-08-07T12:20:33     INFO    GDAL command output:
2024-08-07T12:20:33     INFO    Process completed successfully
2024-08-07T12:20:33     INFO    Results: {'OUTPUT': 'D:/Munca/WB/Geest/St_Lucia/Testing/07082024//temp/roadBuf.shp'}
2024-08-07T12:20:37     INFO    Taking destination CRS EPSG:32620 from layer
2024-08-07T12:20:37     INFO    Setting output type to MultiPolygon
2024-08-07T12:20:37     INFO    Packaging layer 1/1: grid
2024-08-07T12:20:38     INFO    Results: {'OUTPUT': 'output_fcc3cfd1_35e4_46f9_bf10_d891b88ebdf2'}
2024-08-07T12:20:48     INFO    gdal_rasterize -l INPUT -a reclass_val -ts 263.0 487.0 -ot Float32 -of GTiff C:/Users/Dragos/AppData/Local/Temp/processing_YZEcFO/7c2d727edfaa47899b137421033e3897/INPUT.gpkg AT__cycle_paths_lines.tif
2024-08-07T12:20:48     INFO    GDAL command:
2024-08-07T12:20:48     INFO    gdal_rasterize -l INPUT -a reclass_val -ts 263.0 487.0 -ot Float32 -of GTiff C:/Users/Dragos/AppData/Local/Temp/processing_YZEcFO/7c2d727edfaa47899b137421033e3897/INPUT.gpkg AT__cycle_paths_lines.tif
2024-08-07T12:20:48     INFO    GDAL command output:
2024-08-07T12:20:49     CRITICAL    Process returned error code 1
2024-08-07T12:20:49     INFO    Results: {'OUTPUT': 'AT__cycle_paths_lines.tif'}
2024-08-07T12:20:51     INFO    Results: {'OUTPUT': 'output_058ee321_32d7_4d2f_9c4d_90fe9eee2d7f'}
2024-08-07T12:20:51     CRITICAL    ERROR 1: Failed to find field reclass_val on layer INPUT, skipping.

Traceback (most recent call last):
              File "C:\Users/Dragos/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gender_indicator_tool\gender_indicator_tool.py", line 2430, in walkability
              grid_result = processing.run('native:creategrid', grid_params)
              File "C:\PROGRA~1/QGIS 3.32.0/apps/qgis/./python/plugins\processing\tools\general.py", line 106, in run
              return Processing.runAlgorithm(algOrName, parameters, onFinish, feedback, context)
              File "C:\PROGRA~1/QGIS 3.32.0/apps/qgis/./python/plugins\processing\core\Processing.py", line 176, in runAlgorithm
              ret, results = execute(alg, parameters, context, feedback, catch_exceptions=False)
              File "C:\PROGRA~1/QGIS 3.32.0/apps/qgis/./python/plugins\processing\gui\AlgorithmExecutor.py", line 70, in execute
              results, ok = alg.run(parameters, context, feedback, {}, False)
             _core.QgsProcessingException: Could not create layer D:/Munca/WB/Geest/St_Lucia/Testing/07082024//temp/grid.shp: Creation of data source failed (OGR error: D:/Munca/WB/Geest/St_Lucia/Testing/07082024//temp/grid.shp is not a directory.)

@osundwajeff @mvmaltitz

**Comment by mvmaltitz** [comment]
Cycle path results:


![Image](https://github.com/user-attachments/assets/aafe1bf4-4939-474b-9675-f4fc25c9bd15)



![Image](https://github.com/user-attachments/assets/9a21221e-7c55-4474-bfbe-9136ddb714da)

@dragosgontariu

**Comment by mvmaltitz** [comment]
@dragosgontariu

The pixels are now representative of the input lines



![Image](https://github.com/user-attachments/assets/bb95535c-b8f6-41f9-9e97-8197f027d894)

**Comment by javaftw** [comment]
Tested on Windows

![Image](https://github.com/user-attachments/assets/87f5c8aa-4da5-46fe-9d2d-17812968b5ed)

**Comment by dragosgontariu** [comment]
#42
