### ISSUE TITLE
Factor: Active Transport-Subfactor: Block Layout (OSM)

### ISSUE THREAD

**Issue by amyburness** [kartoza/GEEST#50]
````
[out:xml] [timeout:25];
 {{geocodeArea:Saint Lucia}} -> .area_0;
(
    node["landuse"="residential"](area.area_0);
    node["landuse"="commercial"](area.area_0);
    node["landuse"="industrial"](area.area_0);
    node["boundary"="administrative"](area.area_0);
    way["landuse"="residential"](area.area_0);
    way["landuse"="commercial"](area.area_0);
    way["landuse"="industrial"](area.area_0);
    way["boundary"="administrative"](area.area_0);
    relation["landuse"="residential"](area.area_0);
    relation["landuse"="commercial"](area.area_0);
    relation["landuse"="industrial"](area.area_0);
    relation["boundary"="administrative"](area.area_0);
);
(._;>;);
out body;
````
This indicator is composed by calculating the average of these four factors. First, the territory needs to be divided into 100m x 100m rasters.

4. Block Sizes(indicates encouraged walkability)
•	1: Very large block sizes (>1 km)
•	2: Large block sizes (751m - 1 km)
•	3: Moderate block sizes (501m - 750m)
•	4: Small block sizes (251m - 500m)
•	5: Very small block sizes (<250m)

**Comment by carolinamayh** [comment]
Similar to Women's Travel Patterns, Active Transport is assessed by evaluating several subfactors, including block layout. The final score for Active Transport should be the average of the subfactor scores per raster. The tool's interface should not include separate tabs for each subfactor. Please note that the methodology and name for this specific factor, Active Transport, were incorrect in the first version of the GEEST. @osundwajeff

**Comment by dragosgontariu** [comment]
the entire Active Transport factor it's not working

error encountered:

2024-08-07T12:09:25     INFO    GDAL command:
2024-08-07T12:09:25     INFO    gdal_rasterize -l INPUT -a reclass_val -ts 263.0 487.0 -ot Float32 -of GTiff C:/Users/Dragos/AppData/Local/Temp/processing_YZEcFO/525bd6a5d11442ae80a180dadb0f12dc/INPUT.gpkg AT__cycle_paths_lines.tif
2024-08-07T12:09:25     INFO    GDAL command output:
2024-08-07T12:09:25     CRITICAL    Process returned error code 1
2024-08-07T12:09:25     INFO    Results: {'OUTPUT': 'AT__cycle_paths_lines.tif'}
2024-08-07T12:09:27     INFO    Results: {'OUTPUT': 'output_8bb027b8_0234_40ad_bb3d_b0f9e7a42ded'}
2024-08-07T12:09:27     CRITICAL    ERROR 1: Failed to find field reclass_val on layer INPUT, skipping.
2024-08-07T12:20:28     INFO    Results: {'OUTPUT': 'output_ebde8f65_68ff_4f9f_8427_1f44491e0767'}
2024-08-07T12:20:32     INFO    Results: {'OUTPUT': 'D:/Munca/WB/Geest/St_Lucia/Testing/07082024//temp/grid.shp'}
2024-08-07T12:20:33     INFO    ogr2ogr D:/Munca/WB/Geest/St_Lucia/Testing/07082024//temp/roadBuf.shp D:/Munca/WB/Geest/St_Lucia/Testing/07082024//temp/Scored_roads_cycle_paths_lines.shp -dialect sqlite -sql "SELECT ST_Buffer(geometry, 50.0) AS geometry,* FROM """Scored_roads_cycle_paths_lines"""" -f "ESRI Shapefile"
2024-08-07T12:20:33     INFO    GDAL command:
2024-08-07T12:20:33     INFO    ogr2ogr D:/Munca/WB/Geest/St_Lucia/Testing/07082024//temp/roadBuf.shp D:/Munca/WB/Geest/St_Lucia/Testing/07082024//temp/Scored_roads_cycle_paths_lines.shp -dialect sqlite -sql "SELECT ST_Buffer(geometry, 50.0) AS geometry,* FROM """Scored_roads_cycle_paths_lines"""" -f "ESRI Shapefile"
2024-08-07T12:20:33     INFO    GDAL command output:
2024-08-07T12:20:33     INFO    Process completed successfully
2024-08-07T12:20:33     INFO    Results: {'OUTPUT': 'D:/Munca/WB/Geest/St_Lucia/Testing/07082024//temp/roadBuf.shp'}
2024-08-07T12:20:37     INFO    Taking destination CRS EPSG:32620 from layer
2024-08-07T12:20:37     INFO    Setting output type to MultiPolygon
2024-08-07T12:20:37     INFO    Packaging layer 1/1: grid
2024-08-07T12:20:38     INFO    Results: {'OUTPUT': 'output_fcc3cfd1_35e4_46f9_bf10_d891b88ebdf2'}
2024-08-07T12:20:48     INFO    gdal_rasterize -l INPUT -a reclass_val -ts 263.0 487.0 -ot Float32 -of GTiff C:/Users/Dragos/AppData/Local/Temp/processing_YZEcFO/7c2d727edfaa47899b137421033e3897/INPUT.gpkg AT__cycle_paths_lines.tif
2024-08-07T12:20:48     INFO    GDAL command:
2024-08-07T12:20:48     INFO    gdal_rasterize -l INPUT -a reclass_val -ts 263.0 487.0 -ot Float32 -of GTiff C:/Users/Dragos/AppData/Local/Temp/processing_YZEcFO/7c2d727edfaa47899b137421033e3897/INPUT.gpkg AT__cycle_paths_lines.tif
2024-08-07T12:20:48     INFO    GDAL command output:
2024-08-07T12:20:49     CRITICAL    Process returned error code 1
2024-08-07T12:20:49     INFO    Results: {'OUTPUT': 'AT__cycle_paths_lines.tif'}
2024-08-07T12:20:51     INFO    Results: {'OUTPUT': 'output_058ee321_32d7_4d2f_9c4d_90fe9eee2d7f'}
2024-08-07T12:20:51     CRITICAL    ERROR 1: Failed to find field reclass_val on layer INPUT, skipping.

Traceback (most recent call last):
              File "C:\Users/Dragos/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gender_indicator_tool\gender_indicator_tool.py", line 2430, in walkability
              grid_result = processing.run('native:creategrid', grid_params)
              File "C:\PROGRA~1/QGIS 3.32.0/apps/qgis/./python/plugins\processing\tools\general.py", line 106, in run
              return Processing.runAlgorithm(algOrName, parameters, onFinish, feedback, context)
              File "C:\PROGRA~1/QGIS 3.32.0/apps/qgis/./python/plugins\processing\core\Processing.py", line 176, in runAlgorithm
              ret, results = execute(alg, parameters, context, feedback, catch_exceptions=False)
              File "C:\PROGRA~1/QGIS 3.32.0/apps/qgis/./python/plugins\processing\gui\AlgorithmExecutor.py", line 70, in execute
              results, ok = alg.run(parameters, context, feedback, {}, False)
             _core.QgsProcessingException: Could not create layer D:/Munca/WB/Geest/St_Lucia/Testing/07082024//temp/grid.shp: Creation of data source failed (OGR error: D:/Munca/WB/Geest/St_Lucia/Testing/07082024//temp/grid.shp is not a directory.)

@osundwajeff @mvmaltitz

**Comment by osundwajeff** [comment]
Hi @dragosgontariu 
I would like to just confirm the nature of this dataset block length.
As it is, extracting from OSM and using the polyline, the output will be as it was previously.

**Comment by dragosgontariu** [comment]
Hi @osundwajeff 
Please have a look at the polygons attached maybe this input will work. 
[Block layout.zip](https://github.com/user-attachments/files/16610999/Block.layout.zip)

**Comment by mvmaltitz** [comment]
Block layout result:


![Image](https://github.com/user-attachments/assets/b2f179ae-72da-4f4f-bc97-c6d73f863aaf)



![Image](https://github.com/user-attachments/assets/b9079073-36a9-4a14-b8e4-cbed88dc3677)

@dragosgontariu

**Comment by mvmaltitz** [comment]
Result of aggregate:


![Image](https://github.com/user-attachments/assets/4e99f1e9-469c-4aea-9c2a-0114f052ea0c)

@dragosgontariu

**Comment by mvmaltitz** [comment]
@dragosgontariu 
The result now has a range between 0 and 5.


![Image](https://github.com/user-attachments/assets/6e22c59a-604d-4288-8b6b-167300e7a4a4)

**Comment by javaftw** [comment]
Tested on Windows


![Image](https://github.com/user-attachments/assets/e6936b05-763c-4588-8a2e-4c55f2fbab76)

**Comment by dragosgontariu** [comment]
#42
